### ISSUE TITLE
Getting Below Error

### ISSUE THREAD

**Issue by rrjain1** [CasCard/AutoCDSL#2]
Test Event Name
testcdsl

Response
{
  "errorMessage": "name 'datetime' is not defined",
  "errorType": "NameError",
  "requestId": "",
  "stackTrace": [
    "  File \"/var/lang/lib/python3.9/importlib/__init__.py\", line 127, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n",
    "  File \"<frozen importlib._bootstrap>\", line 1030, in _gcd_import\n",
    "  File \"<frozen importlib._bootstrap>\", line 1007, in _find_and_load\n",
    "  File \"<frozen importlib._bootstrap>\", line 986, in _find_and_load_unlocked\n",
    "  File \"<frozen importlib._bootstrap>\", line 680, in _load_unlocked\n",
    "  File \"<frozen importlib._bootstrap_external>\", line 850, in exec_module\n",
    "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\n",
    "  File \"/var/task/lambda_function.py\", line 85, in <module>\n    new_email_date = datetime.fromisoformat('2021-10-22 10:46:37+05:30')\n"
  ]
}

Function Logs
No module named 'selenium'
[ERROR] NameError: name 'datetime' is not defined
Traceback (most recent call last):
  File "/var/lang/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/var/task/lambda_function.py", line 85, in <module>
    new_email_date = datetime.fromisoformat('2021-10-22 10:46:37+05:30')No module named 'selenium'
[ERROR] NameError: name 'datetime' is not defined
Traceback (most recent call last):
  File "/var/lang/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/var/task/lambda_function.py", line 85, in <module>
    new_email_date = datetime.fromisoformat('2021-10-22 10:46:37+05:30')START RequestId: 848a82e3-7d67-441c-b020-3d90f9e7448f Version: $LATEST
Unknown application error occurred
Runtime.Unknown
END RequestId: 848a82e3-7d67-441c-b020-3d90f9e7448f
REPORT RequestId: 848a82e3-7d67-441c-b020-3d90f9e7448f	Duration: 131.82 ms	Billed Duration: 132 ms	Memory Size: 1024 MB	Max Memory Used: 11 MB

Request ID
848a82e3-7d67-441c-b020-3d90f9e7448f

**Comment by CasCard** [comment]
I think you might have forgot to add python lambda layer , can you recheck that ?

**Comment by CasCard** [comment]
Closing the issue due to inactivity
